export const constances = {
    USER_AUTHORIZED: 'USER_AUTHORIZED',
    USER_SIGNIN: 'USER_SIGNIN',
    USER_SIGNIN_ERROR: 'USER_LOGIN_ERROR',
    USER_SIGNOUT: 'USER_SIGNOUT',
    USER_SIGNUP: 'USER_SIGNUP',
    USER_SIGNUP_ERROR: 'USER_SIGNUP_ERROR',

    MESSAGE_FETCH: 'MESSAGE_FETCH',
    MESSAGE_SEND: 'MESSAGE_SEND',
    MESSAGE_DELETE: 'MESSAGE_DELETE',
    MESSAGE_RECEIVE: 'MESSAGE_RECEIVE',
    MESSAGE_SAVE: 'MESSAGE_SAVE',

    REACT_UPDATE: 'REACT_UPDATE',
    
    ROOM_SWITCH: 'ROOM_SWITCH',
    ROOM_FETCH: 'ROOM_FETCH',

    PROFILE_UPDATE: 'PROFILE_UPDATE'
}